const $ = selector => document.querySelector(selector);
const params = new URLSearchParams(location.search);
const outlet = params.get('outlet');
let spinning = false;
function deviceKey() { let key = localStorage.getItem('ohho_spin_device'); if (!key) { key = crypto.randomUUID(); localStorage.setItem('ohho_spin_device', key); } return key; }
function showReward(reward) { $('#rewardLabel').textContent = reward.label; $('#rewardCode').textContent = reward.code; $('#rewardCard').classList.remove('hidden'); $('#spinMessage').textContent = reward.status === 'REDEEMED' ? 'This reward has already been redeemed.' : 'Show your code to the OHHO team before payment.'; }
async function init() { if (!outlet) { $('#spinMessage').textContent = 'Please scan the QR displayed at your OHHO cart.'; return; } try { const res = await fetch(`/api/spin?outlet=${encodeURIComponent(outlet)}`); const data = await res.json(); if (!res.ok) throw new Error(data.error); $('#outletName').textContent = `You are spinning at ${data.outlet.name}`; $('#spinButton').disabled = !data.enabled; $('#spinMessage').textContent = data.enabled ? 'Tap the wheel once to unlock your cart reward.' : 'Spin & Win is paused at this cart.'; } catch (error) { $('#spinMessage').textContent = error.message || 'This QR is not active.'; } }
$('#spinButton').addEventListener('click', async () => { if (spinning || !outlet) return; spinning = true; const button = $('#spinButton'); button.disabled = true; $('#rewardCard').classList.add('hidden'); $('#spinMessage').textContent = 'Spinning your OHHO reward…'; $('#wheel').style.transform = `rotate(${1440 + Math.floor(Math.random() * 720)}deg)`; try { const res = await fetch('/api/spin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'spin', outlet, deviceKey: deviceKey() }) }); const data = await res.json(); await new Promise(resolve => setTimeout(resolve, 3900)); if (!res.ok && !data.reward) throw new Error(data.error); showReward(data.reward); } catch (error) { $('#spinMessage').textContent = error.message || 'Could not spin right now. Please try again.'; button.disabled = false; } finally { spinning = false; } });
init();
